services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - "mongodb:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express:latest
    ports:
      - "3000:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017
    depends_on:
      - mongo
  forms:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.dev
      args:
        SERVICE: forms
    ports:
      - 8080:80
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - ./backend/services/submissions
            - ./backend/services/tenants
        - action: rebuild
          path: ./backend/services/forms/go.mod
  submissions:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.dev
      args:
        SERVICE: submissions
    ports:
      - 8081:80
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - ./backend/services/forms
            - ./backend/services/tenants
        - action: rebuild
          path: ./backend/services/submissions/go.mod
  tenants:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.dev
      args:
        SERVICE: tenants
    ports:
      - 8082:80
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - ./backend/services/forms
            - ./backend/services/submissions
        - action: rebuild
          path: ./backend/services/tenants/go.mod
    depends_on:
      - mongo
volumes:
  mongodb:
