/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignerIndexRouteImport } from './routes/designer/index'
import { Route as FormsFormIdVersionsVersionIdIndexRouteImport } from './routes/forms/$formId/versions/$versionId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerIndexRoute = DesignerIndexRouteImport.update({
  id: '/designer/',
  path: '/designer/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdVersionsVersionIdIndexRoute =
  FormsFormIdVersionsVersionIdIndexRouteImport.update({
    id: '/forms/$formId/versions/$versionId/',
    path: '/forms/$formId/versions/$versionId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designer/': typeof DesignerIndexRoute
  '/forms/$formId/versions/$versionId/': typeof FormsFormIdVersionsVersionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designer': typeof DesignerIndexRoute
  '/forms/$formId/versions/$versionId': typeof FormsFormIdVersionsVersionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/designer/': typeof DesignerIndexRoute
  '/forms/$formId/versions/$versionId/': typeof FormsFormIdVersionsVersionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/designer/' | '/forms/$formId/versions/$versionId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/designer' | '/forms/$formId/versions/$versionId'
  id: '__root__' | '/' | '/designer/' | '/forms/$formId/versions/$versionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignerIndexRoute: typeof DesignerIndexRoute
  FormsFormIdVersionsVersionIdIndexRoute: typeof FormsFormIdVersionsVersionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer/': {
      id: '/designer/'
      path: '/designer'
      fullPath: '/designer/'
      preLoaderRoute: typeof DesignerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/versions/$versionId/': {
      id: '/forms/$formId/versions/$versionId/'
      path: '/forms/$formId/versions/$versionId'
      fullPath: '/forms/$formId/versions/$versionId/'
      preLoaderRoute: typeof FormsFormIdVersionsVersionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignerIndexRoute: DesignerIndexRoute,
  FormsFormIdVersionsVersionIdIndexRoute:
    FormsFormIdVersionsVersionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
