/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignerFormsIndexRouteImport } from './routes/designer/forms/index'
import { Route as DesignerFormsFormIdIndexRouteImport } from './routes/designer/forms/$formId/index'
import { Route as FormsFormIdVersionsVersionIdIndexRouteImport } from './routes/forms/$formId/versions/$versionId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerFormsIndexRoute = DesignerFormsIndexRouteImport.update({
  id: '/designer/forms/',
  path: '/designer/forms/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerFormsFormIdIndexRoute =
  DesignerFormsFormIdIndexRouteImport.update({
    id: '/designer/forms/$formId/',
    path: '/designer/forms/$formId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormsFormIdVersionsVersionIdIndexRoute =
  FormsFormIdVersionsVersionIdIndexRouteImport.update({
    id: '/forms/$formId/versions/$versionId/',
    path: '/forms/$formId/versions/$versionId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designer/forms/': typeof DesignerFormsIndexRoute
  '/designer/forms/$formId/': typeof DesignerFormsFormIdIndexRoute
  '/forms/$formId/versions/$versionId/': typeof FormsFormIdVersionsVersionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designer/forms': typeof DesignerFormsIndexRoute
  '/designer/forms/$formId': typeof DesignerFormsFormIdIndexRoute
  '/forms/$formId/versions/$versionId': typeof FormsFormIdVersionsVersionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/designer/forms/': typeof DesignerFormsIndexRoute
  '/designer/forms/$formId/': typeof DesignerFormsFormIdIndexRoute
  '/forms/$formId/versions/$versionId/': typeof FormsFormIdVersionsVersionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/designer/forms/'
    | '/designer/forms/$formId/'
    | '/forms/$formId/versions/$versionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/designer/forms'
    | '/designer/forms/$formId'
    | '/forms/$formId/versions/$versionId'
  id:
    | '__root__'
    | '/'
    | '/designer/forms/'
    | '/designer/forms/$formId/'
    | '/forms/$formId/versions/$versionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignerFormsIndexRoute: typeof DesignerFormsIndexRoute
  DesignerFormsFormIdIndexRoute: typeof DesignerFormsFormIdIndexRoute
  FormsFormIdVersionsVersionIdIndexRoute: typeof FormsFormIdVersionsVersionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer/forms/': {
      id: '/designer/forms/'
      path: '/designer/forms'
      fullPath: '/designer/forms/'
      preLoaderRoute: typeof DesignerFormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer/forms/$formId/': {
      id: '/designer/forms/$formId/'
      path: '/designer/forms/$formId'
      fullPath: '/designer/forms/$formId/'
      preLoaderRoute: typeof DesignerFormsFormIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/versions/$versionId/': {
      id: '/forms/$formId/versions/$versionId/'
      path: '/forms/$formId/versions/$versionId'
      fullPath: '/forms/$formId/versions/$versionId/'
      preLoaderRoute: typeof FormsFormIdVersionsVersionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignerFormsIndexRoute: DesignerFormsIndexRoute,
  DesignerFormsFormIdIndexRoute: DesignerFormsFormIdIndexRoute,
  FormsFormIdVersionsVersionIdIndexRoute:
    FormsFormIdVersionsVersionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
