/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsSplatRouteImport } from './routes/forms/$'
import { Route as AuthenticationSplatRouteImport } from './routes/authentication/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsSplatRoute = FormsSplatRouteImport.update({
  id: '/forms/$',
  path: '/forms/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationSplatRoute = AuthenticationSplatRouteImport.update({
  id: '/authentication/$',
  path: '/authentication/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authentication/$': typeof AuthenticationSplatRoute
  '/forms/$': typeof FormsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authentication/$': typeof AuthenticationSplatRoute
  '/forms/$': typeof FormsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authentication/$': typeof AuthenticationSplatRoute
  '/forms/$': typeof FormsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/authentication/$' | '/forms/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authentication/$' | '/forms/$'
  id: '__root__' | '/' | '/authentication/$' | '/forms/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticationSplatRoute: typeof AuthenticationSplatRoute
  FormsSplatRoute: typeof FormsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$': {
      id: '/forms/$'
      path: '/forms/$'
      fullPath: '/forms/$'
      preLoaderRoute: typeof FormsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/$': {
      id: '/authentication/$'
      path: '/authentication/$'
      fullPath: '/authentication/$'
      preLoaderRoute: typeof AuthenticationSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticationSplatRoute: AuthenticationSplatRoute,
  FormsSplatRoute: FormsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
