/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificationSplatRouteImport } from './routes/certification/$'
import { Route as AuthenticationSplatRouteImport } from './routes/authentication/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationSplatRoute = CertificationSplatRouteImport.update({
  id: '/certification/$',
  path: '/certification/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationSplatRoute = AuthenticationSplatRouteImport.update({
  id: '/authentication/$',
  path: '/authentication/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authentication/$': typeof AuthenticationSplatRoute
  '/certification/$': typeof CertificationSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authentication/$': typeof AuthenticationSplatRoute
  '/certification/$': typeof CertificationSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authentication/$': typeof AuthenticationSplatRoute
  '/certification/$': typeof CertificationSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/authentication/$' | '/certification/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authentication/$' | '/certification/$'
  id: '__root__' | '/' | '/authentication/$' | '/certification/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticationSplatRoute: typeof AuthenticationSplatRoute
  CertificationSplatRoute: typeof CertificationSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification/$': {
      id: '/certification/$'
      path: '/certification/$'
      fullPath: '/certification/$'
      preLoaderRoute: typeof CertificationSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/$': {
      id: '/authentication/$'
      path: '/authentication/$'
      fullPath: '/authentication/$'
      preLoaderRoute: typeof AuthenticationSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticationSplatRoute: AuthenticationSplatRoute,
  CertificationSplatRoute: CertificationSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
