definitions:
  APIErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
      statusCode:
        type: integer
    type: object
  APIResponse-DataSourceResponse:
    properties:
      data:
        $ref: '#/definitions/DataSourceResponse'
      message:
        type: string
    type: object
  APIResponse-TenantResponse:
    properties:
      data:
        $ref: '#/definitions/TenantResponse'
      message:
        type: string
    type: object
  DataSourceRequest:
    properties:
      attributes:
        type: object
      description:
        maxLength: 500
        type: string
      name:
        maxLength: 75
        type: string
      type:
        $ref: '#/definitions/DataSourceType'
    required:
    - attributes
    - name
    - type
    type: object
  DataSourceResponse:
    properties:
      attributes:
        type: object
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      tenantId:
        type: string
      type:
        $ref: '#/definitions/DataSourceType'
      updatedAt:
        type: string
    type: object
  DataSourceType:
    enum:
    - static
    - scheduled
    - webhook
    - data-lake
    type: string
    x-enum-varnames:
    - DataSourceTypeStatic
    - DataSourceTypeScheduled
    - DataSourceTypeWebhook
    - DataSourceTypeDataLake
  LookupResponse:
    properties:
      label:
        type: string
      value: {}
    type: object
  TenantRequest:
    properties:
      description:
        maxLength: 500
        type: string
      name:
        maxLength: 75
        type: string
    required:
    - name
    type: object
  TenantResponse:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /data-sources:
    get:
      consumes:
      - application/json
      parameters:
      - description: Tenant ID
        in: header
        name: X-Tenant-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/DataSourceResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/APIErrorResponse'
      security:
      - BearerAuth: []
      summary: Get all data sources
      tags:
      - Data Sources
    post:
      consumes:
      - application/json
      description: The attributes field is validated against the schema for the specified
        data source type.
      parameters:
      - description: Tenant ID
        in: header
        name: X-Tenant-ID
        required: true
        type: string
      - description: Create Data Source
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/DataSourceRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/APIResponse-DataSourceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/APIErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a data source
      tags:
      - Data Sources
  /data-sources/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Tenant ID
        in: header
        name: X-Tenant-ID
        required: true
        type: string
      - description: Data Source ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/APIErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete a data source
      tags:
      - Data Sources
    get:
      consumes:
      - application/json
      parameters:
      - description: Tenant ID
        in: header
        name: X-Tenant-ID
        required: true
        type: string
      - description: Data Source ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/DataSourceResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/APIErrorResponse'
      security:
      - BearerAuth: []
      summary: Get a data source by ID
      tags:
      - Data Sources
    put:
      consumes:
      - application/json
      description: The attributes field is validated against the schema for the specified
        data source type.
      parameters:
      - description: Tenant ID
        in: header
        name: X-Tenant-ID
        required: true
        type: string
      - description: Data Source ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Data Source
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/DataSourceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/APIResponse-DataSourceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/APIErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/APIErrorResponse'
      security:
      - BearerAuth: []
      summary: Update a data source
      tags:
      - Data Sources
  /data-sources/{id}/look-ups:
    get:
      consumes:
      - application/json
      description: Returns key-value pairs suitable for populating selection inputs
        from the specified data source.
      parameters:
      - description: Tenant ID
        in: header
        name: X-Tenant-ID
        required: true
        type: string
      - description: Data Source ID
        in: path
        name: id
        required: true
        type: string
      - description: Optional parameters for look-up retrieval, such as query parameters
          for external fetches or payload for webhook calls.
        in: query
        name: params
        type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/LookupResponse'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/APIErrorResponse'
      security:
      - BearerAuth: []
      summary: Get data source look-ups
      tags:
      - Data Sources
  /tenants:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/TenantResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/APIErrorResponse'
      security:
      - BearerAuth: []
      summary: Get all tenants
      tags:
      - Tenants
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Tenant
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/TenantRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/APIResponse-TenantResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/APIErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a tenant
      tags:
      - Tenants
  /tenants/{id}:
    delete:
      consumes:
      - application/json
      description: All data sources belonging to the tenant will also be deleted.
      parameters:
      - description: Tenant ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/APIErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete a tenant
      tags:
      - Tenants
    get:
      consumes:
      - application/json
      parameters:
      - description: Tenant ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TenantResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/APIErrorResponse'
      security:
      - BearerAuth: []
      summary: Get a tenant by ID
      tags:
      - Tenants
    put:
      consumes:
      - application/json
      parameters:
      - description: Tenant ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Tenant
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/TenantRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/APIResponse-TenantResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/APIErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/APIErrorResponse'
      security:
      - BearerAuth: []
      summary: Update a tenant
      tags:
      - Tenants
securityDefinitions:
  BearerAuth:
    description: 'Bearer JWT. Format: "Bearer <token>"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
